config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  # Error pages
  %w( 404 422 500 503 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  # Resque web interface
  resque_web_constraint = lambda do |request|
    current_user = User.find_by(id: request.session[:user_id])
    current_user && current_user.is?(:admin)
  end

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/admin/resque'
  end

  # Active Admin
  ActiveAdmin.routes(self)

  # Custom admin routes
  namespace :admin do
    resources :demo_videos do
      resources :features
    end

    resources :id_card_requests do
      resources :comments
      resources :nodes
    end

    resources :id_card_templates do
      resources :nodes
    end

    resources :important_date_types do
      resources :important_date_type_programs
    end

    resources :look_books do
      resources :photos
    end

    resources :products do
      resources :photos
    end

    resources :schools do
      resources :addresses
      resources :convocations
      resources :photos
      resources :program_notes
    end

    resources :services do
      resources :features
      resources :photos
    end

    resources :settings do
      collection do
        patch :update_all
      end
    end

    resources :sittings do
      resources :features
    end
  end

  # API routes
  namespace :api do
    namespace :v1 do
      resources :id_card_requests, only: [:index, :update]
    end
  end

  # Root
  root 'root#show'

  resources :bookings, only: [] do
    collection do
      get :thank_you
    end
  end

  resources :contact_requests, only: [:create]

  resources :feedbacks, only: [:new, :create] do
    collection do
      get :thank_you
    end
  end


  resources :employees, only: [:index]

  resources :id_card_requests, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      get :find
    end

    member do
      get :thank_you
    end
  end

  resources :products, only: [:index]

  resources :schools, only: [:index, :show] do
    collection do
      get :book
      get :find
    end

    resources :bookings, only: [:create, :edit, :update] do
      member do
        get :confirmation
      end

      resources :payments, only: [:new, :create]
    end

    resources :events, only: [:index]

    resources :programs, only: [:show]

    resources :registrations, only: [:new, :create] do
      collection do
        get :confirmation
      end
    end
  end

  resources :services, only: [:show]

  resource :session

  # Static page routes
  StaticController::STATIC_PAGES.each do |page|
    get "/#{page}", to: "static##{page}", as: "#{page}_static"
  end

  # Load balancer health check
  get '/health_check' => 'health_check#index'
end

app/models/id_card_request.rb
class IdCardRequest < ActiveRecord::Base
  include AASM

  # Associations
  belongs_to :id_card_template
  belongs_to :school
  has_many :nodes, -> { order(:position) }, as: :owner, dependent: :destroy
  has_many :comments, as: :owner, dependent: :destroy

  # Attributes
  accepts_nested_attributes_for :nodes
  accepts_nested_attributes_for :comments

  # Attachments
  mount_uploader :result_photo, PhotoUploader
  mount_uploader :result_pdf, FileUploader

  # Validations
  validates_presence_of :id_card_template
  validates_presence_of :school
  validates_presence_of :attention_of
  validates_presence_of :attention_of_email
  validates_format_of :attention_of_email, with: RegexHelper::EMAIL, message: 'Please enter a valid e-mail address.'

  validate :unique_request

  # API Scopes
  scope :state, -> state { where(state: state) }

  # Callbacks
  before_validation :ensure_uuid

  # State machine
  aasm column: :state, whiny_transitions: false do
    state :pending, initial: true
    state :requested
    state :errored
    state :rendered
    state :processed
    state :shipped

    event :request, after: [:clear_renders, :render_request] do
      transitions from: :pending, to: :requested, after: :send_new_request
      transitions from: :errored, to: :requested
      transitions from: :rendered, to: :requested
      transitions from: :processed, to: :requested
      transitions from: :shipped, to: :requested
    end

    event :error do
      transitions from: :requested, to: :errored
    end

    event :render do
      transitions from: :requested, to: :rendered
      transitions from: :errored, to: :rendered
    end

    event :process do
      transitions from: :rendered, to: :processed
    end

    event :ship do
      transitions from: :processed, to: :shipped
    end
  end

  private

  def unique_request
    return if student_number.blank?

    # All requests for same student, where they are not past the state of rendered
    existing_requests = IdCardRequest.where(school: school, student_number: student_number)
                                     .where(state: ['pending', 'requested', 'rendered'])

    # Don't count the self record
    existing_requests = existing_requests.where('id != ?', id) if id

    errors.add(:base, 'A request already exists for this student ID #') if existing_requests.count > 0
  end

  def ensure_uuid
    self.uuid ||= SecureRandom.urlsafe_base64
  end

  def send_new_request
    IdCardRequestMailer.new_request(self).deliver_now
  end

  def clear_renders
    self.remove_result_photo!
    self.remove_result_pdf!

    self.save
  end

  def render_request
    Resque.enqueue(IdCardGenerator, id_card_request_id: self.id)
  end
end

app/controllers/api/v1/id_card_requests_controller.rb
module Api
  module V1
    class IdCardRequestsController < Api::V1::BaseController
      # Before filters
      before_filter :fetch_id_card_request, only: [:update]

      # Scopes
      has_scope :state

      def index
        @id_card_requests = paginate(apply_scopes(IdCardRequest), per_page: PAGE_SIZE)

        render json: @id_card_requests, include: params[:include], status: 200
      end

      def update
        @id_card_request.assign_attributes(id_card_request_params)

        if @id_card_request.save
          render json: @id_card_request, include: params[:include], status: 200
        else
          error_422(nil, @id_card_request.errors)
        end
      end

      def fetch_id_card_request
        @id_card_request = IdCardRequest.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        return error_404
      end

      private

      def id_card_request_params
        params.require(:id_card_request).permit(
          :state
        )
      end
    end
  end
end

app/controllers/id_card_requests_controller.rb
require 'open-uri'
require 'addressable/uri'

class IdCardRequestsController < ApplicationController
  # Before filters
  before_filter :ensure_authenticated,    except: [:index]
  before_filter :check_setting,           only: [:find, :new, :create]
  before_filter :fetch_id_card_templates, only: [:find]
  before_filter :fetch_id_card_template,  only: [:new, :create, :update]
  before_filter :fetch_school,            only: [:new, :create, :update]
  before_filter :fetch_subject_data,      only: [:new]
  before_filter :prepare_params,          only: [:create]
  before_filter :fetch_id_card_request,   only: [:show, :edit, :update, :thank_you]

  # Constants
  JUNIOR_API_PATH = '/api/subjects'
  CONFIG          = Rails.application.secrets

  def index
  end

  def find
  end

  def new
    @id_card_request = IdCardRequest.new

    # Attach extra variables
    @id_card_request.id_card_template = @id_card_template
    @id_card_request.school = @school
    @id_card_request.student_name = "#{@subject['last_name']}, #{@subject['first_name']}" if @subject
    @id_card_request.student_number = params[:id_card_request][:student_number]
    @id_card_request.attention_of_email = current_user.email
    @id_card_request.comments.build(user: current_user)

    # Generate all the nodes
    @id_card_template.nodes.order(:position).each do |node|
      new_node = node.dup

      # Generate all the phrases
      node.phrases.each do |phrase|
        new_phrase = phrase.dup

        new_node.phrases << new_phrase
      end

      populate_node(new_node, node)

      @id_card_request.nodes << new_node
    end
  end

  def create
    @id_card_request = IdCardRequest.new(id_card_request_params)

    # Attach school
    @id_card_request.school = @school

    if @id_card_request.save
      # find name fields and normalize name then attach it to the student name field if there is no subject object
      if @id_card_request.student_name.blank?
        @id_card_request.student_name = generate_student_name(@id_card_request)
        @id_card_request.save
      end

      @id_card_request.request!

      redirect_to thank_you_id_card_request_path(@id_card_request.uuid)
    else
      flash[:error] = 'Unable to complete request. Review the errors below.'
      render action: 'new', status: 422
    end
  end

  def edit
  end

  def update
    if @id_card_request.update_attributes(id_card_request_params)
      @id_card_request.request!

      redirect_to id_card_request_path(@id_card_request.uuid)
    else
      flash[:error] = 'Unable to complete request. Review the errors below.'
      render action: 'edit', status: 422
    end
  end

  def show
  end

  def thank_you
  end

  private

  def check_setting
    # Allow admins to always request an id card
    if Setting.show_replace_id_card != '1' && !current_user&.is?(:admin)
      flash[:notice] = 'Sorry, you can not currently request an ID Card.'
      return redirect_to root_path
    end
  end

  def fetch_id_card_templates
    schools = School.all

    # Teachers only have access to their school
    if current_user.is?('teacher') && current_user.school
      schools = [current_user.school]
    end

    @id_card_templates = IdCardTemplate.joins(:school).where('schools.id IN (?)', schools.map(&:id)).order('schools.name')
  end

  def fetch_id_card_template
    @id_card_template = IdCardTemplate.find(params.dig(:id_card_request, :id_card_template_id))
  rescue ActiveRecord::RecordNotFound
    return render_error(404, 'The requested ID card is unavailable.')
  end

  def fetch_school
    @school = @id_card_template.school

    return render_error(404, 'The requested school could not be found.') unless @school
  end

  def fetch_subject_data
    return @subject = nil if params[:id_card_request][:student_number].blank?

    addressable = Addressable::URI.new

    addressable.query_values = {
      subject_number: params[:id_card_request][:student_number],
      gallery_name: @school.name
    }

    uri = "#{CONFIG.junior_api_host}#{JUNIOR_API_PATH}?#{addressable.query}"

    response = open(uri, http_basic_authentication: [CONFIG.junior_api_user, CONFIG.junior_api_password]).read

    subjects = JSON.parse(response)['subjects']

    # Remove the students who doesn't have a photo from the APE Junior API response

    subjects = subjects.select { |subject| subject['photo_url'] != nil }

    @subject = subjects[0]
  end

  def fetch_id_card_request
    @id_card_request = IdCardRequest.find_by_uuid!(params[:id])
  rescue ActiveRecord::RecordNotFound
    return render_error(404)
  end

  def id_card_request_params
    params.require(:id_card_request).permit(
      :id_card_template_id,
      :school_id,
      :student_name,
      :student_number,
      :attention_of,
      :attention_of_email,
      nodes_attributes: [
        :id,
        :type,
        :name,
        :x,
        :y,
        :width,
        :height,
        :font_family,
        :point_size,
        :alignment,
        :uppercase,
        :node_photo,
        :remote_node_photo_url,
        :crop_x,
        :crop_y,
        :crop_width,
        :crop_height,
        :color,
        :junior_field,
        :remote_mask_url,
        phrases_attributes: [
          :id,
          :name,
          :junior_field,
          :prefix,
          :text,
          :suffix,
        ]
      ],
      comments_attributes: [
        :user_id,
        :custom_text,
        :text
      ]
    )
  end

  def populate_node(node, old_node)
    case node.type
    when 'Nodes::Text'
      node.phrases.each do |phrase|
        if @subject
          phrase.text = @subject[node.junior_field] if node.junior_field
          phrase.text = @subject[phrase.junior_field] if phrase.junior_field
          phrase.text = "#{@subject['first_name']} #{@subject['last_name']}" if phrase.name == 'Name (First and Last)'
          phrase.text = "#{@subject['last_name']}, #{@subject['first_name']}" if phrase.name =='Name (Lastname, Firstname)'
          phrase.text = @school.name if phrase.name == 'School Name'
        end
      end
    when 'Nodes::Photo'
      if @subject
        node.remote_node_photo_url = @subject['photo_url']
      else
        node.remote_node_photo_url = node.node_photo_url
      end

      node.remote_mask_url = old_node.mask_url if old_node&.mask_url
    end
  end

  def prepare_params
    # Take uploaded photos over Junior imported photos
    params.dig(:id_card_request, :nodes_attributes)&.each do |node|
      node[1][:remote_node_photo_url] = nil if node[1][:node_photo]
    end

    # Remove blank comments
    params[:id_card_request][:comments_attributes] = nil if params.dig(:id_card_request, :comments_attributes, 0.to_s.to_sym, :text).blank?
  end

  def generate_student_name(id_card_request)
    name_node = id_card_request.nodes.find_by(name: 'Name')

    if name_node && name_node.phrases.count > 1
      # one single name node split into two phrases
      first_name = name_node.phrases.find_by(name: 'First Name').text
      last_name = name_node.phrases.find_by(name: 'Last Name').text
      "#{last_name}, #{first_name}"
    elsif name_node
      # one single name node with one phrase
      name = name_node.phrases.first.text
      normalize_name(name)
    else
      # separate first and last name nodes
      first_name = id_card_request.nodes.find_by(name: 'First Name').phrases.first.text
      last_name = id_card_request.nodes.find_by(name: 'Last Name').phrases.first.text
      "#{last_name}, #{first_name}"
    end
  end

  def normalize_name(name)
    return name.split(' ').reverse.join(', ') unless name.include?(',')
    name
  end
end

app/views/id_card_requests/_form.html.erb
<%
  template_serializer = IdCardTemplateSerializer.new(id_card_template)
  request_serializer  = IdCardRequestSerializer.new(id_card_request)
  template_adapter    = ActiveModel::Serializer::Adapter.create(template_serializer)
  request_adapter     = ActiveModel::Serializer::Adapter.create(request_serializer, include: 'nodes, nodes.phrases')
  path    = id_card_request.persisted? ? id_card_request_path(id_card_request.uuid) : id_card_requests_path
  method  = id_card_request.persisted? ? :patch : :post
%>

<div class="id-card-requests-new">
  <div class="container">
    <p>
      Please modify the data below to continue.
    </p>

    <%= render partial: 'shared/form_error_messages', locals: { object: id_card_request } %>

    <%= simple_form_for id_card_request, url: path, method: method do |f| %>
      <%= f.input :id_card_template_id, as: :hidden %>
      <%= f.input :school_id, as: :hidden %>
      <%= f.input :student_name, as: :hidden %>
      <%= f.input :student_number, as: :hidden %>

      <%= react_component('IdCardRequest',
        idCardTemplate: template_adapter.as_json,
        idCardRequest: request_adapter.as_json) %>

      <%= render partial: 'nodes/form', locals: { f: f } %>


      <%= f.input :attention_of %>
      <%= f.input :attention_of_email, hint: 'A confirmation email will be sent to you after you submit the request.' %>

      <%= f.simple_fields_for :comments do |c| %>
        <%= c.input :user_id, as: :hidden %>

        <%= c.input :text, label: 'Reason', as: :select, collection: Comment::SELECTIONS, selected: 'New Student', input_html: { onchange: "handleReasonSelect(this);" } %>
        <%= c.input :custom_text, input_html: { id: :custom_comment }, placeholder: 'type your reason here', as: :hidden %>
      <% end %>

      <p>
        ID cards are printed and shipped every Friday. You should receive them the following mid week via Canada Post.
      </p>

      <p>
        Please note: any image uploaded on this form is only for an ID Card; it will not appear in the yearbook, pictorial, or MyEdBC.
      </p>

      <div class="center">
        <%= f.submit 'Submit', class: 'submit-form link link--button link--button-maroon' %>
      </div>
    <% end %>

  </div>

  <%= render partial: 'modals/codabar_modal', locals: { id: 'codabar-1' } %>
</div>

<script language="javascript">
  var idCardRequest = <%= request_adapter.to_json.html_safe %>;
  function initializeTextNode(node, index) {
    if (node.attributes.type !== 'Nodes::Text') return;
    node.relationships.phrases.data.forEach(function(phrase, p_index) {
      $("#id_card_request_nodes_attributes_" + index + "_phrases_attributes_" + p_index + "_text").on("keyup", function(event) {
        updateFontSize(node, index);
      });
    });
    updateFontSize(node, index);
  };
  // Handle dynamically updating font size
  function updateFontSize(node, index) {
    var value = "";
    // Build the text from all the phrases
    node.relationships.phrases.data.forEach(function(phrase, p_index) {
      var text    =  $("#id_card_request_nodes_attributes_" + index + "_phrases_attributes_" + p_index + "_text").val();
      var prefix  =  $("#id_card_request_nodes_attributes_" + index + "_phrases_attributes_" + p_index + "_prefix").val();
      var suffix  =  $("#id_card_request_nodes_attributes_" + index + "_phrases_attributes_" + p_index + "_suffix").val();
      if (text) {
        value += prefix + text + suffix
      }
    });
    var resizer = $('<span />').hide().appendTo(document.body);
    resizer.html(value);
    var $size = $("#id_card_request_nodes_attributes_" + index + "_point_size");
    var initial_size = node.attributes.point_size
    // Add properties that affect size
    resizer.css('font-family', node.attributes.font_family);
    resizer.css('font-size', initial_size);
    resizer.css('white-space', 'pre');
    var size = initial_size + 1;
    while (resizer.width() > node.attributes.width) {
      size = parseInt(resizer.css('font-size'));
      resizer.css('font-size', size - 1);
    }
    while (resizer.height() > node.attributes.height) {
      size = parseInt(resizer.css('font-size'));
      resizer.css('font-size', size - 1);
    }
    // Set the final size in the input
    $size.val(size - 1);
    resizer.remove();
  };
  function initializePhotoNode(node, index) {
    if (node.attributes.type !== 'Nodes::Photo') return;
    $("#id_card_request_nodes_attributes_" + index + "_node_photo").on("change", function(event) {
      handleFileSelect(index, event);
    });
    // This initialization of the cropper is done in the react components
  };
  function handleFileSelect(index, event) {
    var $img, $output, file, files, $photo, i, len, reader;
    $photo = $("#id_card_request_nodes_attributes_" + index + "_node_photo");
    $output = $photo.parent().next();
    $img = $($output.find('img')[0]);
    files = event.target.files;
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      if (!file.type.match('image.*')) continue;
      reader = new FileReader;
      reader.onload = function(event) {
        return setPhotoPreview(index, $output, event.target.result);
      };
      reader.readAsDataURL(file);
    }
  };
  function setPhotoPreview(index, $output, src) {
    var img = document.createElement('img');
    img.onload = function() {
      return initializeCropper(index);
    };
    img.className = 'node-photo-preview__thumb';
    img.src = src;
    $output.html(img);
  }
  function initializeCropper(index) {
    var $photo = $("#id_card_request_nodes_attributes_" + index + "_node_photo");
    var $output = $photo.parent().next();
    var $img = $($output.find('img')[0]);
    var width = $("#id_card_request_nodes_attributes_" + index + "_width").val();
    var height = $("#id_card_request_nodes_attributes_" + index + "_height").val();
    $img.cropper({
      viewMode: 1,
      rotatable: false,
      scalable: false,
      zoomable: false,
      aspectRatio: width / height,
      checkCrossOrigin: false,
      data: {
        x:      parseInt($("#id_card_request_nodes_attributes_" + index + "_crop_x").val()) || 0,
        y:      parseInt($("#id_card_request_nodes_attributes_" + index + "_crop_y").val()) || 0,
        width:  parseInt($("#id_card_request_nodes_attributes_" + index + "_crop_width").val()) || 9999,
        height: parseInt($("#id_card_request_nodes_attributes_" + index + "_crop_height").val()) || 9999
      },
      preview: "div#photo-preview-" + index,
      crop: function(event) {
        updateCrops(index, event);
      },
      built: function(event) {
        // Force a re-render of the react component
        ReactRailsUJS.mountComponents();
      }
    });
  };
  function updateCrops(index, event) {
    var x = parseInt(event.x);
    var y = parseInt(event.y);
    var width = parseInt(event.width);
    var height = parseInt(event.height);
    $("#id_card_request_nodes_attributes_" + index + "_crop_x").val(x)
    $("#id_card_request_nodes_attributes_" + index + "_crop_y").val(y)
    $("#id_card_request_nodes_attributes_" + index + "_crop_width").val(width)
    $("#id_card_request_nodes_attributes_" + index + "_crop_height").val(height)
  }
  var nodes = idCardRequest.included.filter(function(item) {
    return (item.attributes.type === 'Nodes::Text' ||
            item.attributes.type === 'Nodes::Photo');
  })
  // Initialize all text node dynamics
  nodes.forEach(initializeTextNode)
  // Initialize all photo node dynamics
  nodes.forEach(initializePhotoNode)
  $(':input').on("keyup", function(event) {
    // Force a re-render of the react component
    ReactRailsUJS.mountComponents();
  });
</script>
<script>
  function handleReasonSelect(that) {
    if ($(that).val() === 'Other') {
      $('.id_card_request_comments_text').addClass('string optional').removeClass('hidden')
      $('#custom_comment').addClass('string optional').removeClass('hidden').attr('type', 'text')
    } else {
      $('.id_card_request_comments_text').addClass('hidden').removeClass('string optional')
      $('#custom_comment').addClass('hidden').removeClass('string optional').attr('type', 'hidden')
    }
  };
</script>

app/views/id_card_requests/_help.html.erb
<div class="content">
  <h2 class="headline">
    Need Help?
  </h2>
  <p>
    Please feel free to <%= mail_to 'idcard@artona.com', 'contact us', class: 'link link--dark link--underlined' %>
    if you have any questions.
  </p>
</div>

app/views/id_card_requests/_meta.html.erb
<h2 class="headline">Meta</h2>

<ul class="list list--vertical">
  <li><strong>Reference:</strong> <%= id_card_request.id %></li>
  <li><strong>Status:</strong> <%= render partial: 'shared/status_tag', locals: { text: id_card_request.state } %></li>
  <p class="paragraph--small">
    <% if id_card_request.rendered? %>
      Your ID card request is waiting to be printed.
    <% elsif id_card_request.processed? %>
      Your ID card request has been printed.
    <% end %>
  </p>
  <li><strong>Requester:</strong> <%= id_card_request.attention_of %></li>
  <li><strong>Requester Email:</strong> <%= id_card_request.attention_of_email %></li>
</ul>

app/views/id_card_requests/edit.html.erb
<div class="id-card-requests-edit">
  <div class="hero" style="background-image: url(<%= image_path('heroes/artona.png') %>)">
    <div class="container">
      <div class="center hero__content hero__content--right">
        <h1 class="hero__title">Edit ID Card Request</h1>
      </div>
    </div>
  </div>

  <div class="content">
    <%= render partial: 'id_card_requests/form', locals: { id_card_request: @id_card_request, id_card_template: @id_card_request.id_card_template } %>
  </div>

  <div class="container center">
    <%= render partial: 'id_card_requests/help' %>
  </div>
</div>

app/views/id_card_requests/find.html.erb
<div class="id-card-requests-find">
  <div class="hero" style="background-image: url(<%= image_path('heroes/artona.png') %>)">
    <div class="container">
      <div class="center hero__content hero__content--right">
        <h1 class="hero__title">ID Card Request</h1>
      </div>
    </div>
  </div>

  <div class="content">
    <div class="container">
      <p>
        Please provide the necessary data below to get started.
      </p>


      <%= simple_form_for :id_card_request, url: new_id_card_request_path, html: { method: :get } do |f| %>
        <%= f.input :id_card_template_id, label: "ID Card Template", as: :select, input_html: { class: 'select2' }, collection: @id_card_templates.map { |ict| ["#{ict.school.name} - #{ict.name}", ict.id] }, include_blank: false %>
        <%= f.input :student_number, required: false %>

        <div class="center">
          <%= f.submit 'Continue', class: 'link link--button link--button-maroon' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="content center">
    <div class="container">
      <h2 class="headline">Manual Form</h2>
      <p>
        An offline form can also be filled out by downloading it
        <%= link_to 'here', 'https://s3.amazonaws.com/assets.artona.com/documents/IdCard+Authorization+Form+for+Schools+-+Re-Order+Form.pdf', class: 'link link--dark link--underlined', target: '_blank' %>.
      </p>
    </div>
  </div>

  <div class="container center">
    <%= render partial: 'id_card_requests/help' %>
  </div>
</div>

app/views/id_card_requests/index.html.erb
<div class="id-card-requests-index">
  <div class="hero" style="background-image: url(<%= image_path('heroes/artona.png') %>)">
    <div class="container">
      <div class="center hero__content hero__content--right">
        <h1 class="hero__title">ID Card Requests</h1>
      </div>
    </div>
  </div>

  <div class="content">
    <div class="container center">
      <h3 class="headline">What Would You Like To Do?</h3>

      <p>
        Generate an ID Card online <%= link_to 'here', find_id_card_requests_path %>.
      </p>

      <p>
        Fill out an offline form by downloading it
        <%= link_to 'here', 'https://s3.amazonaws.com/assets.artona.com/documents/IdCard+Authorization+Form+for+Schools+-+Re-Order+Form.pdf', class: 'link link--dark link--underlined', target: '_blank' %>.
      </p>
    </div>
  </div>

  <div class="container center">
    <%= render partial: 'id_card_requests/help' %>
  </div>
</div>

app/views/id_card_requests/new.html.erb
<div class="id-card-requests-new">
  <div class="hero" style="background-image: url(<%= image_path('heroes/artona.png') %>)">
    <div class="container">
      <div class="center hero__content hero__content--right">
        <h1 class="hero__title">ID Card Request</h1>
      </div>
    </div>
  </div>

  <div class="content">
    <%= render partial: 'id_card_requests/form', locals: { id_card_request: @id_card_request, id_card_template: @id_card_template } %>
  </div>

  <div class="container center">
    <%= render partial: 'id_card_requests/help' %>
  </div>
</div>

app/views/id_card_requests/show.html.erb
<div class="id-card-requests-thank-you">
  <div class="hero" style="background-image: url(<%= image_path('heroes/idcards.jpg') %>)">
    <div class="container">
      <div class="center hero__content hero__content--right">
        <h1 class="hero__title">ID Card Request</h1>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="content">
      <h2 class="headline">Result</h2>

      <% if @id_card_request.requested? %>
        <p>
          This ID card is still being rendered. Check back soon!
        </p>
      <% else %>
        <%= image_tag @id_card_request.result_photo_url, class: 'id-card-request__preview-image' %>

        <% if @id_card_request.result_pdf_url %>
          <p>
            <%= link_to 'Download PDF', @id_card_request.result_pdf_url, target: '_blank', class: 'link link--underlined link--dark' %>
          </p>
        <% end %>
      <% end %>

      <% if !(@id_card_request.processed? || @id_card_request.shipped?) %>
        <p>
          <%= link_to 'Click here', edit_id_card_request_path(@id_card_request.uuid), class: 'link link--underlined link--dark' %>
          to EDIT your ID card request.
        </p>
      <% else %>
        <p>
          Your card has already been processed or shipped and is no longer editable at this time. Please make a new ID card request or contact us at <a class="link link--underlined link--dark" href="mailto:idcard@artona.com">idcard@artona.com</a> for assistance.
        </p>
      <% end %>

      <%= render partial: 'id_card_requests/meta', locals: { id_card_request: @id_card_request } %>
    </div>
  </div>

  <div class="container center">
    <%= render partial: 'id_card_requests/help' %>
  </div>
</div>

app/views/id_card_requests/thank_you.html.erb
<div class="id-card-requests-thank-you">
  <div class="hero" style="background-image: url(<%= image_path('heroes/idcards.jpg') %>)">
    <div class="container">
      <div class="center hero__content hero__content--right">
        <h1 class="hero__title">Thank You</h1>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="content">
      <h2 class="headline">Successfully Submitted!</h2>
      <p>
        A confirmation email has been sent to <%= @id_card_request.attention_of_email %>
        for your records.
      </p>

      <p>
        To submit another request, use
        the <%= link_to 'Replace ID Card Form', find_id_card_requests_path, class: 'link link--underlined link--dark' %>.
        If you have questions please email
        <a class="link link--underlined link--dark" href="mailto:idcard@artona.com">idcard@artona.com</a>
      </p>

      <p>
        <%= link_to 'Click here', id_card_request_path(@id_card_request.uuid), class: 'link link--underlined link--dark' %>
        to VIEW your ID card request status.
      </p>

      <% if !(@id_card_request.processed? || @id_card_request.shipped?) %>
        <p>
          <%= link_to 'Click here', edit_id_card_request_path(@id_card_request.uuid), class: 'link link--underlined link--dark' %>
          to EDIT your ID card request.
        </p>
      <% else %>
        <p>
          Your card has already been processed or shipped and is no longer editable at this time. Please make a new ID card request or contact us at <a class="link link--underlined link--dark" href="mailto:idcard@artona.com">idcard@artona.com</a> for assistance.
        </p>
      <% end %>

      <p>We print ID cards and deliver them to schools every two weeks.</p>
    </div>

    <div class="content">
      <%= render partial: 'id_card_requests/meta', locals: { id_card_request: @id_card_request } %>
    </div>
  </div>

  <div class="container center">
    <%= render partial: 'id_card_requests/help' %>
  </div>
</div>