config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  # Error pages
  %w( 404 422 500 503 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  # Resque web interface
  resque_web_constraint = lambda do |request|
    current_user = User.find_by(id: request.session[:user_id])
    current_user && current_user.is?(:admin)
  end

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/admin/resque'
  end

  # Active Admin
  ActiveAdmin.routes(self)

  # Custom admin routes
  namespace :admin do
    resources :demo_videos do
      resources :features
    end

    resources :id_card_requests do
      resources :comments
      resources :nodes
    end

    resources :id_card_templates do
      resources :nodes
    end

    resources :important_date_types do
      resources :important_date_type_programs
    end

    resources :look_books do
      resources :photos
    end

    resources :products do
      resources :photos
    end

    resources :schools do
      resources :addresses
      resources :convocations
      resources :photos
      resources :program_notes
    end

    resources :services do
      resources :features
      resources :photos
    end

    resources :settings do
      collection do
        patch :update_all
      end
    end

    resources :sittings do
      resources :features
    end
  end

  # API routes
  namespace :api do
    namespace :v1 do
      resources :id_card_requests, only: [:index, :update]
    end
  end

  # Root
  root 'root#show'

  resources :bookings, only: [] do
    collection do
      get :thank_you
    end
  end

  resources :contact_requests, only: [:create]

  resources :feedbacks, only: [:new, :create] do
    collection do
      get :thank_you
    end
  end


  resources :employees, only: [:index]

  resources :id_card_requests, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      get :find
    end

    member do
      get :thank_you
    end
  end

  resources :products, only: [:index]

  resources :schools, only: [:index, :show] do
    collection do
      get :book
      get :find
    end

    resources :bookings, only: [:create, :edit, :update] do
      member do
        get :confirmation
      end

      resources :payments, only: [:new, :create]
    end

    resources :events, only: [:index]

    resources :programs, only: [:show]

    resources :registrations, only: [:new, :create] do
      collection do
        get :confirmation
      end
    end
  end

  resources :services, only: [:show]

  resource :session

  # Static page routes
  StaticController::STATIC_PAGES.each do |page|
    get "/#{page}", to: "static##{page}", as: "#{page}_static"
  end

  # Load balancer health check
  get '/health_check' => 'health_check#index'
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  # Class methods
  def self.method_missing(method_name, *args, &block)
    if method_name.match(/=$/)
      method_name = method_name[0..-2]

      record = find_record(method_name) || Setting.new(key: method_name)
      record.value = args[0].to_yaml
      record.save!
    else
      record = find_record(method_name)
      record ? YAML.load(record.value) : nil
    end
  end

  private

  def self.find_record(method_name)
    self.where(key: method_name).first
  end
end

app/views/admin/settings/index.html.erb
<%= simple_form_for :settings, url: update_all_admin_settings_path, html: { method: :patch }, builder: ActiveAdmin::FormBuilder do |f| %>
  <%= f.inputs 'Seasons' do %>
    <%= f.input :ordering_season, input_html: { value: Setting.ordering_season }, hint: 'Date must be in format YYYY/MM/DD', required: false %>
  <% end %>

  <%= f.inputs 'ID Cards' do %>
    <%= f.input :show_replace_id_card, as: :boolean, input_html: { checked: Setting.show_replace_id_card == '1' }, label: 'Enable the Replacement ID Card Request Form.' %>
  <% end %>

  <% if current_user.is?(:admin) %>
    <%= f.inputs 'Payments' do %>
      <%= f.input :exact_password, label: 'E-Xact Password', input_html: { value: Setting.exact_password }, required: false %>
    <% end %>
  <% end %>

  <% if current_user.is?(:admin) %>
    <%= f.inputs 'Olark' do %>
      <%= f.input :olark_code, input_html: { value: Setting.olark_code }, required: false %>
    <% end %>
  <% end %>

  <%= f.inputs 'API' do %>
    <%= f.input :api_user, input_html: { value: Setting.api_user } %>
    <%= f.input :api_password, input_html: { value: Setting.api_password } %>
  <% end %>

  <%= submit_tag 'Save All Settings' %> <%= link_to 'Cancel', admin_dashboard_path %>
<% end %>