config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  # Error pages
  %w( 404 422 500 503 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  # Resque web interface
  resque_web_constraint = lambda do |request|
    current_user = User.find_by(id: request.session[:user_id])
    current_user && current_user.is?(:admin)
  end

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/admin/resque'
  end

  # Active Admin
  ActiveAdmin.routes(self)

  # Custom admin routes
  namespace :admin do
    resources :demo_videos do
      resources :features
    end

    resources :id_card_requests do
      resources :comments
      resources :nodes
    end

    resources :id_card_templates do
      resources :nodes
    end

    resources :important_date_types do
      resources :important_date_type_programs
    end

    resources :look_books do
      resources :photos
    end

    resources :products do
      resources :photos
    end

    resources :schools do
      resources :addresses
      resources :convocations
      resources :photos
      resources :program_notes
    end

    resources :services do
      resources :features
      resources :photos
    end

    resources :settings do
      collection do
        patch :update_all
      end
    end

    resources :sittings do
      resources :features
    end
  end

  # API routes
  namespace :api do
    namespace :v1 do
      resources :id_card_requests, only: [:index, :update]
    end
  end

  # Root
  root 'root#show'

  resources :bookings, only: [] do
    collection do
      get :thank_you
    end
  end

  resources :contact_requests, only: [:create]

  resources :feedbacks, only: [:new, :create] do
    collection do
      get :thank_you
    end
  end


  resources :employees, only: [:index]

  resources :id_card_requests, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      get :find
    end

    member do
      get :thank_you
    end
  end

  resources :products, only: [:index]

  resources :schools, only: [:index, :show] do
    collection do
      get :book
      get :find
    end

    resources :bookings, only: [:create, :edit, :update] do
      member do
        get :confirmation
      end

      resources :payments, only: [:new, :create]
    end

    resources :events, only: [:index]

    resources :programs, only: [:show]

    resources :registrations, only: [:new, :create] do
      collection do
        get :confirmation
      end
    end
  end

  resources :services, only: [:show]

  resource :session

  # Static page routes
  StaticController::STATIC_PAGES.each do |page|
    get "/#{page}", to: "static##{page}", as: "#{page}_static"
  end

  # Load balancer health check
  get '/health_check' => 'health_check#index'
end

app/views/modals/_booking_modal.html.erb
<% id ||= 'modal-1' %>

<div id="<%= id %>" class="modal modal--light">
  <div class="booking-modal-container">
    <div class="container">
      <h2 class="modal__title modal__title--dark">
        <% if @school.name == 'Digital Business Portraits' %>
          Continue to Digital Business Portrait booking?
        <% else %>
          What is your student number?
        <% end %>
        <i class="fa fa-close float-right modal__close modal__close--dark"></i>
      </h2>

      <div class="modal__content">
        <%= simple_form_for :booking, url: school_bookings_path(@school), html: { method: :post } do |f| %>
          <%= f.input :sitting_type, as: :hidden, input_html: { value: sitting.sitting_type } %>
          <% if @school.name == 'Digital Business Portraits' %>
            <%= f.input :graduation_year, as: :hidden, input_html: { value: "20#{Utils.photography_year}" }  %>
            <%= f.input :student_number, as: :hidden, input_html: { value: rand(1..1000).to_s } %>
          <% else %>
            <%= f.input :graduation_year, collection: Utils.graduation_years, include_blank: false, selected: "20#{Utils.photography_year}", input_html: { class: 'select2', style: 'width:100%;' } %>
            <%= f.input :student_number %>
          <% end %>
          <%= f.submit 'Continue', class: 'link link--button link--button-maroon' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/modals/_codabar_modal.html.erb
<% id ||= 'modal-1' %>

<div id="<%= id %>" class="modal modal--light">
  <div class="codabar-modal-container">
    <div class="container">
      <h2 class="modal__title modal__title--dark">
        Generate a Codabar value
        <i class="fa fa-close float-right modal__close modal__close--dark"></i>
      </h2>

      <div class="input string required codabar__input">
        <label class="string required" for="codabar_input">
          Student ID #
        </label>

        <input class="string required" type="text" name="codabar_input" />

        <span class="hint">
          <strong>Copy and Paste</strong> the calculated value into all barcode/codebar form fields.
        </span>
      </div>

      <div class="codabar__output">
        <h4 class="headline headline--sub">Calculated value</h4>

        <p>
          Type the student number in the input box above to see the calculated value here. (Barcode/Codabar)
        </p>
      </div>
    </div>
  </div>
</div>

app/views/modals/_contact_request_modal.html.erb
<%
  id ||= 'modal-1'
  to_emails ||= 'csr@artonagroup.com'
%>

<div id="<%= id %>" class="modal modal--light">
  <div class="contact-request-container">
    <div class="container">
      <h2 class="modal__title modal__title--dark">
        Get in touch!
        <i class="fa fa-close float-right modal__close modal__close--dark"></i>
      </h2>

      <div class="modal__content">
        <%= render partial: 'contact_requests/form', locals: { to_emails: to_emails } %>
      </div>
    </div>
  </div>
</div>

app/views/modals/_grad_portraits_modal.html.erb
<% id ||= 'modal-1' %>

<div id="<%= id %>" class="modal modal--light">
  <div class="grad-portraits-modal-container">
    <div class="container">
      <h2 class="modal__title modal__title--dark">
        How do Grad Portraits work?
        <i class="fa fa-close float-right modal__close modal__close--dark"></i>
      </h2>

      <p class="center hide-small">
        <%= image_tag 'portraits_infographic.png' %>
      </p>

      <p class="center show-small">
        <%= image_tag 'portraits_infographic_mobile.png' %>
      </p>

      <p class="center">
        <%= link_to 'Book Now', book_schools_path, class: 'link link--button link--button-maroon' %>
      </p>
    </div>
  </div>
</div>

app/views/modals/_look_book_modal.html.erb
<% id ||= 'modal-1' %>

<div id="<%= id %>" class="modal modal--light">
  <div class="look-book-modal-container">
    <div class="container">
      <h2 class="modal__title modal__title--dark">
        <%= look_book.title || 'Look Book' %>

        <i class="fa fa-close float-right modal__close modal__close--dark"></i>
      </h2>

      <div class="modal__content">
        <%= render partial: 'look_books/list_item', locals: { look_book: look_book } %>
      </div>

      <div class="content center">
        <p>
          Check out our <%= link_to 'how to prepare', prepare_static_path, class: 'link link--dark link--underlined' %>
          guide for all your preparation needs!
        </p>
      </div>
    </div>
  </div>
</div>

app/views/modals/_video_modal.html.erb
<% id ||= 'modal-1' %>
<% title ||= '' %>
<% source ||= '' %>

<div id="<%= id %>" class="modal">
  <div class="container">
    <h2 class="modal__title">
      <%= title %>
      <i class="fa fa-close float-right modal__close"></i>
    </h2>

    <div class="modal__content center">
      <video class="modal__video" controls>
        <source src="<%= source %>">

        Your browser does not support HTML5 video.
      </video>
    </div>
  </div>
</div>